### ISSUE TITLE
Broken link + missing example

### ISSUE THREAD

**Issue by kkluwehkg** [MicrosoftDocs/visualstudio-docs.de-de#12] opened 2018-09-06 07:00 UTC
The Link "Install Visual Studio 2017 on low bandwidth or unreliable network environments." seems to be broken.
... and an example for the mentioned commandline "You can use the command line to create a local cache" is missing.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Erstellen einer Offlineinstallation von Visual Studio - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment] 2018-09-06 20:17
This is by design; we have retired the "Install Visual Studio 2017 on low bandwidth or unreliable network environments" page and folded its contents into the revised [Create an offline installation of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017) page. (The link goes to the En-us version of the page; this page in other locales should be updated with the revisions, soon.)

**Comment by LisandroSu** [comment] 2018-09-06 23:16
Hello, @<contributor's GITHUB name>,
 
Thank you for your feedback.

We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team

**Closed by LisandroSu** 2018-09-06 23:16 UTC
Labels: Source Issue
